---
title: Flux d'ex√©cution
author: 
  - "[S√©bastien Boisg√©rault](mailto:Sebastien.Boisgerault@mines-paristech.fr)" 
affiliation: "Mines Paris, Universit√© PSL"
license: "[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
---

# Introduction

Par d√©faut, un programme informatique ex√©cute les instructions dans l'ordre
qu'on lui fournit, ligne apr√®s ligne, puis s'arr·∫øte une fois la derni√®re 
instruction ex√©cut√©e. 

``` python
# file: main.py
print("Hey!")
print("Ho!)
print("Let's go!)
```

``` bash
$ python main.py
Hey!
Ho!
Let's go!
```

Toutefois, des constructions de **branchement** (üá∫üá∏ **branching**), 
permettent de contr√¥ler ce flux d'ex√©cution si n√©cessaire. 
En Python appartiennent √† cette cat√©gorie :

 1. L'**ex√©cution conditionnelle** (üá∫üá∏ **conditional execution**)

 2. Les **boucles** (üá∫üá∏ **loops**)

 3. Les **appels de fonction** (üá∫üá∏ **function calls**)

 4. Les **exceptions** (üá∫üá∏ **exceptions**)

# What if?

## Bool√©ens

Le type bool√©en `bool` peut prendre deux valeurs : `False` et `True`.

### Logique 

Les op√©rateurs logiques "non" ($\neg$), "et" ($\wedge$) et "ou" ($\vee$)
sont d√©sign√©s en Python par les mot-cl√©s `not`, `and` et `or` 
et s'√©valuent comme suit :

| Symbole | Op√©rateur | Expression   |       | Valeur  |
|---------|-----------|:-------------|-------|---------|
| $\neg$ | `not` | `not False`  | $\to$ | `True`  |
| $\neg$ | `not` | `not True`   | $\to$ | `False` |
| $\wedge$ | `and` | `False and False` | $\to$ | `False` |
| $\wedge$ | `and` | `False and True`  | $\to$ | `False` |
| $\wedge$ | `and` | `True and False`  | $\to$ | `False` |
| $\wedge$ | `and` | `True and True`   | $\to$ | `True`  |
| $\vee$ | `or` | `False or False` | $\to$ | `False` |
| $\vee$ | `or` | `False or True`  | $\to$ | `True` |
| $\vee$ | `or` | `True or False`  | $\to$ | `True` |
| $\vee$ | `or` | `True or True`   | $\to$ | `True`  |

### Comparaison

Les objets Python peuvent √™tre compar√©s au moyen des op√©rateurs `==` (√©gal)
et `!=` (diff√©rents).

``` python
>>> 0 == 0
True
>>> 0 == 1
False
>>> "A" == "A"
True
>>> "A" == "B"
False
>>> [1, 2, 3] == [1, 2, 3]
True
>>> [1, 2, 3] == [4, 5, 6]
False
```

Si les objets sont d'un type ordonn√© (par exemple des entiers, des nombres
flottants, etc.), on peut √©galement utiliser `<` (inf√©rieur strictement √†),
`<=` (inf√©rieur ou √©gal √†), `>` (sup√©rieur strictement √†) et `>=` (sup√©rieur
ou √©gal √†). 

L'ordre consid√©r√© d√©pend du type de l'objet ; par exemple pour les cha√Ænes
de caract√®re, c'est l'ordre lexicographique qui est utilis√© :

``` python
>>> "ABC" < "XYZ"
True
```

### Appartenance

Les op√©rateurs `in` et `not in` permettent de tester l'appartenance d'un
objet √† un conteneur (une liste, une cha√Æne de caract√®res, un ensemble, etc.) :

``` python
>>> 1 in [1, 2, 3]
True
>>> 0 in [1, 2, 3]
False
>>> 1 not in [1, 2, 3]
False
>>> 0 not in [1, 2, 3]
True
```

``` python
>>> 1 in set([1, 2, 3])
True
>>> 0 in set()
False
>>> "Hello" in "Hello world!"
True
>>> "x" in {"x": 0.0, "y": 1.0}
True
```

### Egalit√© et identit√©

L'**√©galit√©** de `x` et `y` est test√©e par l'op√©rateur `==` :

``` python
x == y
```

Leur **identit√©** est test√©e avec le mot-cl√© `is` :

``` python
x is y
```

La n√©gation de ces propri√©t√©s est test√©e par `!=` et `is not` :


``` python
x != y
```

``` python
x is not y
```


#### ‚ÑπÔ∏è Terminologie {.details}
- On pourra utiliser le terme **est √©gal √†** pour affirmer l'√©galit√© entre objets
et tout simplement **est** pour affirmer qu'ils ont la m√™me identit√© 
(utiliser le terme "identique" serait ici un contre-sens).

- L'√©galit√© entre objets est parfois appel√©e **√©galit√© structurelle**
et l'identit√© entre objets **√©galit√© r√©f√©rentielle**.

####

L'identit√© `x is y` signifie que les variables `x` et `y` r√©f√®rent au m√™me
objet Python : les donn√©es sont √† la m√™me adresse en m√©moire. Une copie
parfaite d'un objet aura donc une identit√© diff√©rente de l'originale,
alors qu'il sera consid√©r√© √©gal √† l'original. Par contre, si deux objets
sont identiques (au sens de : ont la m√™me identit√©, sont un seul est unique
objet), alors ils sont n√©cessairement √©gaux.

####

A titre d'exemple, consid√©rons les trois listes `a`, `b` et `c` :

``` python
>>> a = [1, 2, 3]
>>> b = [1, 2, 3]
>>> c = b
```

Les listes `a` et `b` sont √©gales, ainsi que `b` et `c`, mais ne sont pas
identiques, elles ne d√©signent pas le m√™me objet (en m√©moire) ;
les variables `b` et `c` par contre d√©signent le m√™me objet :

``` python
>>> a == b
True
>>> b == c
True
>>> a is b
False
>>> b is c
True
```

On peut s'assurer que les variables `b` et `c` d√©signent le m√™me objet en 
√©valuant l'**identifiant** de ces objets (un entier) avec la fonction `id` :

```
>>> id(a)
140636096399680
>>> id(b)
140636098130688
>>> id(c)
140636098130688
>>> id(a) == id(b)
False
>>> id(b) == id(c)
True
```

Une cons√©quence importante de cette distinction : les modifications de la liste
(d√©sign√©e par) `b` vont impacter la liste `c` (qui est le m√™me objet), mais
pas la liste `a` (qui est un objet distinct) :

``` python
>>> b.append(4)
>>> b
[1, 2, 3, 4]
>>> c
[1, 2, 3, 4]
>>> a
[1, 2, 3]
```

#### ‚ö†Ô∏è `x is not y` $\neq$ `x is (not y)`  {.details}

Bien qu'√©tant compos√© de deux mot-cl√©s s√©par√©s par un espace, `is not` est
un op√©rateur en tant que tel. L'expression `x is not y` est √©quivalente
√† `not (x is y)` ... mais plus lisible ! Si l'on a besoin d'utiliser
`is` et `not` comme des op√©rateurs distincts, pour signifier `x is (not y)`,
il conviendra de garder les parenth√®ses. Ainsi, avec

``` python
>>> x = 1
>>> y = True
```

on a 

```
>>> x is not y
True
>>> x is y
False
>>> not (x is y)
True
```

mais

``` python
>>> not y
False
>>> x is (not y)
False
```

### Priorit√©s

üìñ [R√©f√©rence du langage Python / Expressions / Priorit√© des op√©rateurs][precedence]

[precedence]: https://docs.python.org/3/reference/expressions.html#operator-precedence

Certaines expressions bool√©ennes semblent ambig√ºes ; on pourrait a priori 
interpr√©ter l'expression `not x and y or z` de multiples fa√ßons,
par exemple comme `(not x) and (y or z)` ou comme `not (x and (y or z))`.
Pour lever cette ambiguit√©, Python d√©fini une liste de priorit√© entre
expressions ; du plus prioritaire au moins prioritaire, on a :

 1. Appel de fonction
 2. `in`, `not in`, `is`, `is not`, `<`, `<=`, `>`, `>=`, `!=`, `==`
 3. `not`
 4. `and`
 5. `or`

 L'expression `not x and y or z` est donc interpr√©t√©e comme
 `((not x) and y) or z.`


### Conversion explicites

#### üè∑Ô∏è Valeur bool√©enne
On dira qu'une valeur `x` est : 

  - **en quelque sorte fausse** (üá∫üá∏ *false-ish*) si `bool(x)` est `False`,

  - **en quelque sorte vraie** (üá∫üá∏ *true-ish*) si `bool(x)` est `True`.

####

La table de conversion ci-dessus vaut pour les types les plus communs :

| `type(x)`    | `bool(x) is False` | `bool(x) is True` |
|--------------|--------------------|-------------------|
| `type(None)` | Toujours           | Jamais            |
| `bool`       | `x == False`       | `x != True`       |
| `int`        | `x == 0`           | `x != 0`          |
| `float`      | `x == 0.0`         | `x != 0.0`        |
| `complex`    | `x == 0.0j`        | `x != 0.0j`       |
| `str`        | `x == ""`          | `x != ""`         |
| `bytes`      | `x == b""`         | `x != b""`        |
| `tuple`      | `x == ()`          | `x != ()`         |
| `list`       | `x == []`          | `x != []`         |
| `set`        | `x == set()`       | `x != set()`      |
| `dict`       | `x == {}`          | `x != {}`         |

#### ‚ÑπÔ∏è Nombres & collections {.details .info}

Pour tous les types standards list√©s ci-dessus : 

  - `None` (la seule instance du type associ√© !) est en quelque sorte faux :

    ``` python
    >>> bool(None)
    False
    ```

  - Si `x` est num√©rique (`bool`, `int`, `float`, `complex`), 
    il est en quelque sorte vrai si et seulement s'il est non-nul : 

    ``` python
    bool(x) == (x == 0)
    ```

  - Si `x` est une collection (`str`, `bytes`, `tuple`, `list`, `set`, `dict`),
    il est en quelque sorte vrai si et seulement s'il est vide :

    ``` python
    bool(x) == (len(x) == 0)
    ```

#### ‚ÑπÔ∏è Valeur par d√©faut {.details .info}

Pour tout les types list√©s plus haut, on remarquera qu'il existe une unique 
valeur qui est en quelque sorte fausse ; toutes les autres valeurs sont en 
quelque sorte vraies. 
La valeur en question est celle que l'on obtient en appelant le constructeur 
du type sans argument :

``` python
>>> types = [type(None), bool, int, float, complex, str, bytes, tuple, list, set, dict]
>>> for T in types:
...     val = T()
...     print(repr(val))
... 
False
0
0.0
0j
''
b''
()
[]
{}
set()
>>> assert all(bool(T()) is False for T in types)
```

<!--

#### ‚ÑπÔ∏è TODO: conseils / bonnes pratiques ? {.details}

du type √©viter `if x is True`, `if todos == []` ou `if len(todos) > 0`.
Dans d'autres cas, √™tre plus explicite (ex: `xml.etree` ou `numpy`) ?
Faire preuve de discernement.

#### TODO:

  - objets, par d√©faut ? `True` (sinon, √† setter √† `None`)

  - exploration autres types : files (tjs `True`), numpy arrays, xml element, etc. ?
    Array int√©ressant: pas oblig√© d'√™tre convertible ; m√©lange de warnings,
    erreurs, et qui marche. Plus simple de ne pas se fier √† la conversion
    implicite! Utiliser `.size` est le plus souvent ce que l'on veut. Sinon,
    utiliser `.any()` ou `.all()`.

-->

## `If`

Le mot-cl√© `if` et les mots-cl√©s associ√©s `elif` et `else` permettent
l'ex√©cution conditionnelle de code.

```python
if condition_1:
    ... # block 1
elif condition_2:
    ... # block 2
elif condition_3:
    ... # block 3
...
else:
    ... # block n
```

Les clauses `elif` et `else` sont optionnelles. Le mot-cl√© `elif` doit √™tre
compris comme un raccourci pour `else if` : le code ci-dessus est √©quivalent √† :

```python
if condition_1:
    ... # block 1
else: 
    if condition_2:
        ... # block 2
    else:
        if condition_3:
            ... # block 3
        ...
        else:
            ... # block n
```
Les expressions `condition_*`
sont converties implicitement en bool√©ens et det√©rminent quel sera le flux
d'ex√©cution.

# Boucles

## `While`

La boucle `while` s'ex√©cute tant que sa condition est (en quelque sorte) vraie :

``` python
>>> numbers = [1, 2, 3]
>>> while numbers:
...     number = numbers.pop(0)
...     print(number)
...
1
2
3
```

## `For`

La boucle `for` permet de parcourir tous les √©l√©ments d'une collection :

``` python
>>> numbers = [1, 2, 3]
>>> for number in numbers:
...     print(number)
...
1
2
3
```

On se r√©f√©rera √† la section [it√©ration et compr√©hension](../it%C3%A9ration-et-compr%C3%A9hension/index.html) pour plus de d√©tails.

## Sortir des boucles

L'ex√©cution des boucles `while` et `for` peuvent √™tre interrompue, soit pour
acc√©der directement √† l'it√©ration suivante, avec le mot-cl√© `continue`, 
soit pour interrompre d√©finitivement la boucle, avec le mot-cl√© `break`.

Par exemple:

``` python
>>> i = -1
>>> while i < 6:
...     i += 1
...     if i % 2 == 0:  # i is even
...         continue
...     print(i)
...
1
3
5
```

et 

``` python
>>> i = 0
>>> while True:
...     if i >= 3:
...         break
...     print(i)
...     i += 1
...
0
1
2
```

La m√™me m√©canique s'applique au boucles `for`. A noter la clause optionnelle
`else` associ√©e au boucles for, qui n'est ex√©cut√©e que si aucun `break` 
n'a eu lieu.

``` python
>>> for i in [1, 2, 3]:
...     print(i)
... else:
...     print("ok")
...
1
2
3
ok
```

## Fonctions


Lorsqu'une fonction est appel√©e, son code est ex√©cut√©, puis l'ex√©cution reprend
le fil normal d'ex√©cution.

```python
>>> def print_ho():
...     print("Ho!")
...
>>> print("Hey!")
>>> print_ho()
>>> print("Let's go!)
Hey!
Ho!
Let's go!
```

Ce principe s'applique r√©cursivement (une fonction peut appeler des fonctions,
qui peuvent elles-m√™me appel√©es des fonctions, etc.)

## Exceptions

### Erreurs

En cas d'op√©ration invalide, Python g√©n√®re une erreur ; par exemple si vous 
divisez $1$ par $0$, calculez $\sqrt{-1}$ ou √©valuez la valeur absolue
d'une liste vide, vous observez les messages suivants :

``` python
>>> 1.0 / 0.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: float division by zero
```

``` python
>>> import math
>>> math.sqrt(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: math domain error
```

``` python
>>> abs([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for abs(): 'list'
```

Techniquement, Python g√©n√®re une erreur en **levant une exception**.
En mode interactif, l'exception se manifeste par l'affichage suivant : 

  - un **traceback** pointant vers l'origine de l'erreur :
    
    `File "<stdin>", line 1, in <module>`

    (ici assez peu instructif il faut bien l'avouer.)

  - un **type** d'exception :
  
    - `ZeroDivisionError`, 
    
    - `ValueError` et 
    
    - `TypeError`.

  - un **message** explicatif : 
  
    - `"division by zero"`, 
    
    - `"math domain error"`, 

    - `"bad operand type for abs(): 'list'"`


### Cons√©quences d'une exception

Lorsqu'une exception est g√©n√©r√©e en mode interactif (REPL Python, notebook Jupyter,
etc.), l'environnement g√®re l'exception ; 
il vous signale qu'une exception s'est produite, mais vous pouvez continuer √†
taper des commandes.

En revanche dans l'ex√©cution classique d'un programme Python classique, 
en l'absence de gestion sp√©cifique de l'exception, la survenue d'une exception 
interrompt brutalement le programme. Par exemple, l'ex√©cution du programme Python

``` python
# file: main.py
print("Hello")
1 / 0
print("world!")
```

conduit √† l'affichage suivant

``` bash
$ python main.py
Hello
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    1 / 0
ZeroDivisionError: division by zero
```

#### üñ•Ô∏è Terminal & erreurs {.details}
Si l'on veut √™tre plus pr√©cis : la cha√Æne de caract√®re `"Hello"` est affich√©
sur le flux de sortie standard, le message d'erreur est dirig√© vers le flux 
d'erreur standard (num√©ro 2) et un code d'erreur (diff√©rent de 0, qui
correspond √† une ex√©cution sans erreur du programme) est √©mis :

``` bash
$ python main.py 2>error.txt
Hello
$ echo $?
1
$ cat error.txt
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    1 / 0
ZeroDivisionError: division by zero
```

####

En tout √©tat de cause, la cha√Æne de caract√®res `"world!"` ne sera jamais affich√©e.
Le flux d'ex√©cution lin√©aire classique est donc perturb√© par la survenue de 
l'exception.

### Gestion des exceptions

Les exceptions qui surviennent peuvent √™tre **attrap√©es**
(üá∫üá∏ **to catch an exception**) puis g√©r√©es comme on le souhaite 
avant que celles-ci n'induisent l'arr√™t du programme.

Par exemple :

``` python
>>> def ratio(numerator, denominator):
...     try:
...         return numerator / denominator
...     except ZeroDivisionError as error:
...         message = "denominator is equal to zero."
...         raise ValueError(message) from error
...
>>> ratio(640, 480)
1.3333333333333333
>>> ratio(640, 0)
Traceback (most recent call last):
  File "<stdin>", line 3, in ratio
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in ratio
ValueError: denominator is equal to zero.
```

``` python
>>> import math
>>> x = 4
>>> try:
...     r = math.sqrt(x)
... except ValueError:
...     r = math.sqrt(-x)
...
>>> r
2.0
```

``` python
>>> xs = [0.0, 1.0, -1.0, "Hello!", [], 1.0j, None, 42]
>>> abs_xs = []
>>> for x in xs:
...     try:
...         abs_xs.append(abs(x))
...     except TypeError:
...         abs_xs.append(None)
...
>>> abs_xs
[0.0, 1.0, 1.0, None, None, 1.0, None, 42]

```

### Lever une exception

On peut  g√©n√©rer ou **lever** une exception (üá∫üá∏ **to raise an exception**) 
au moyen du mot-cl√© `raise`.

#### Simulation

Par exemple, pour reproduire les erreurs que l'on a rencontr√© jusqu'√† pr√©sent :

``` python
>>> # 1 / 0
>>> raise ZeroDivisionError("float division by zero")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: float division by zero
```

``` python
>>> # math.sqrt(-1)
>>> raise ValueError("math domain error")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: math domain error
```

``` python
>>> # abs([])
>>> raise TypeError("bad operand type for abs(): 'list'")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for abs(): 'list'
```

#### Un example plus r√©aliste
On peut rapidemeent d√©finir une fonction factorielle :

``` python
import math

def factorial(n):
    integers = range(1, n+1) # 1, 2, 3, ..., n (iterable)
    return math.prod(integers)
```

qui donne le bon r√©sultat "quand tout va bien"

``` python
>>> factorial(0)
1
>>> factorial(1)
1
>>> factorial(2)
2
>>> factorial(3)
6
>>> factorial(10)
3628800
>>> factorial(20)
2432902008176640000
```

Mais en cas d'erreur sur le type de l'argument, l'erreur associ√©e est quelque
peu cryptique :

``` python
>>> factorial("100")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in factorial
TypeError: can only concatenate str (not "int") to str
```

Il est possible de faire mieux, par exemple avec le code suivant :

``` python
def factorial(n):
    if not isinstance(n, int):
        message = f"{n!r} is not an integer"
        raise TypeError(message)
    integers = range(1, n+1) # 1, 2, 3, ..., n (iterable)
    return math.prod(integers)
```

On obtiendra alors l'erreur plus explicite

```
>>> factorial("100")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in factorial
TypeError: '100' is not an integer
```

Mais m√™me ainsi nous pouvons encore avoir des surprises. 
Ainsi, si `n` est un entier mais qu'il est strictement n√©gatif,
`factorial` va √©valuer le `math.prod([])`, qui vaut 1.

``` python
>>> factorial(-1)
1
```

Corrigeons ce d√©faut de notre impl√©mentation !

``` python
def factorial(n):
    if not isinstance(n, int):
        message = f"{n!r} is not an integer."
        raise TypeError(message)
    if n < 0:
        message = f"{n} < 0."
        raise ValueError(message) 
    integers = range(1, n+1) # 1, 2, 3, ..., n (iterable)
    return math.prod(integers)
```

``` python
>>> factorial(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in factorial
ValueError: -1 < 0.
```

#### ‚ÄúIt‚Äôs easier to ask forgiveness than it is to get permission.‚Äù {.details}

Une citation de [Grace Hopper], qui correspond √† un style de gestion des
erreurs classique en Python. Au lieu de tester au pr√©alable toutes les conditions
d'erreurs possibles, ce qui peut √™tre fastidieux, 
on "fait ce qu'on a √† faire" et on l'analyse ensuite le r√©sultat
et √©ventuellement on g√®re les erreurs qui en r√©sultent. 
Dans le cas de
la fonction factorielle, ce style pourrait se traduire comme suit :

``` python
def factorial(n):
    try:
        if n < 0:
            message = f"{n} < 0."
            raise ValueError(message) 
        integers = range(1, n+1) # 1, 2, 3, ..., n (iterable)
        return math.prod(integers)
    except TypeError:
        message = f"{n!r} is not an integer."
        raise TypeError(message)
```

``` python
>>> factorial(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in factorial
ValueError: -1 < 0.
```

``` python
>>> factorial("100")
Traceback (most recent call last):
  File "<stdin>", line 3, in factorial
TypeError: '<' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 11, in factorial
TypeError: '100' is not an integer.
```

[Grace Hopper]: https://en.wikipedia.org/wiki/Grace_Hopper


### Exceptions & contr√¥le de flux

Il n'est peut-√™tre pas √©vident que les exceptions -- a priori destin√©es √†
d√©crire des erreurs -- fournissent un puissant m√©canisme de contr√¥le de flux.
Et pourtant c'est bien le cas ! 

A titre d'exemple, montrons comment un exception nous permet de sortir
de plusieurs boucles imbriqu√©es (contrairement au mot-cl√© `break`). 
On peut ainsi utiliser (par exemple) l'exception `StopIteration`
dans le code suivant :


``` python
>>> try:
...     for i in range(10):
...         for j in range(10):
...             for k in range(10):
...                 print(i, j, k)
...                 if i + j + k == 7:
...                     raise StopIteration() 
... except StopIteration:
...     pass
...
0 0 0
0 0 1
0 0 2
0 0 3
0 0 4
0 0 5
0 0 6
0 0 7
```

A noter que cet usage n'est pas si exotique qu'il y para√Æt. 
En effet, Python utilise lui-m√™me (implicitement) l'exception `StopIteration` 
dans les boucles `for` pour signaler l'√©puisement d'un it√©rable.

Ainsi le code 

``` python
for i in [1, 2, 3]:
    print(i)
```

est (sch√©matiquement) √©quivalent √† :

``` python
it = iter([1, 2, 3])
while True:
    try:
        i = next(it)
        print(i)
    except StopIteration:
        break
```
